# Numpy-Numercial Python      
It is linear algebra library for python       
Why Numpy? It is incredibly fast, consumes less memory compared to list.

In [1]:
import numpy as np       #Import numpy package

In [2]:
b = [1,2,3]             #List

In [3]:
a = np.array(b)         #Conversion of list to numpy array
a

array([1, 2, 3])

In [4]:
a.shape                 #Shape of vector #.shape is an attribute not method

(3,)

In [5]:
a.ndim                  #Dimension of vector

1

In [6]:
a.dtype                 #DataType

dtype('int32')

In [7]:
m = [[1,2,3], [4,5,6], [7,8,9]]  #List within list
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
a2 = np.array(m)

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a2.shape                #Row and column of matrix

(3, 3)

In [11]:
a2.dtype

dtype('int32')

In [12]:
a2.ndim                #Dimension of given matrix

2

In [13]:
np.random.randn(4,)   #randn takes value from normal distribution

array([-0.97306213,  0.58273452,  0.25361365, -1.51499635])

In [14]:
np.random.rand(4)     #rand takes from uniform distribution

array([0.85298646, 0.53769403, 0.50690198, 0.64408479])

In [15]:
np.random.randn(5,4)  #For 2D matrix with random values # Row and column

array([[ 0.03029204,  0.18986615,  1.12472409, -2.49090498],
       [ 1.72660497, -0.6242338 ,  0.55688524,  0.39419923],
       [ 0.73300053,  1.07921682,  0.09565346, -0.4942309 ],
       [-0.23631891, -2.04914493, -0.38618851,  1.25123602],
       [-0.41219502,  0.17048384, -0.31842546,  0.90548372]])

In [16]:
np.random.randn(3,5,4) #3D (How many matrix,row,column)

array([[[-1.43948122, -0.99967772,  0.58728037, -0.84046989],
        [-0.36355348,  0.12903453, -0.44529918, -0.02745101],
        [ 1.08074376, -1.45188702, -1.14959906, -1.63408128],
        [ 1.08879253,  0.17863922,  0.23959198,  0.14734495],
        [-0.60212632,  0.32870493, -0.19481773,  0.78690081]],

       [[-0.30957244,  0.72959675,  0.14517553,  0.79548576],
        [ 0.63581264, -1.96446956, -0.10982763, -0.97928157],
        [-0.53823169,  1.00659789,  1.43291639, -1.00233271],
        [ 0.5089238 ,  1.11960229,  1.43448691, -0.59055896],
        [-0.74614174, -1.04528336, -0.53396228,  0.46339166]],

       [[-0.04762936,  0.52109123, -1.77856149, -1.65418776],
        [ 1.21873395,  1.00944261,  4.01050194, -0.21203604],
        [-0.05864995, -0.17451656,  1.54370861, -0.85270491],
        [-0.40163459, -1.22106941, -0.19182582, -0.8126433 ],
        [-0.47508462, -0.17373419, -1.95945688,  0.84775758]]])

In [17]:
np.random.randint(1,10)   #Generate random integer between 1 and 10 (not including 10) 

5

In [18]:
np.random.randint(1,10,5)  #(Between 1 and 10, generate 5 numbers)

array([6, 6, 2, 2, 3])

In [19]:
np.random.randint(1,10,(5,)) #(Between 1 and 10, (row,))

array([6, 2, 8, 2, 8])

In [20]:
np.random.randint(1,10,(3,3)) #(Between 1 and 10, generate 3 by 3 matrix)

array([[8, 5, 5],
       [2, 4, 8],
       [8, 3, 4]])

In [21]:
np.random.seed(10)      #To generate pseudo random values we use seed 
np.random.randint(1,10,7)

array([5, 1, 2, 1, 2, 9, 1])

In [22]:
arr = np.arange(12) #a-array and range -- arange.. Array's range
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr.shape

(12,)

In [24]:
arr.reshape(3,4)    #reshape fuction reshapes #reshape according to same elements here 12 elements = 3*4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
s = np.arange(0,10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
s[::]    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
s[-1]

9

In [28]:
j = np.arange(10,20)
j

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
j[0:5]= 100     #If you want to change first 5 values of array we can use slicing 

In [30]:
j

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19])

In [31]:
h = j[:7]

In [32]:
h

array([100, 100, 100, 100, 100,  15,  16])

In [33]:
h[:]=5
h

array([5, 5, 5, 5, 5, 5, 5])

In [34]:
j

array([ 5,  5,  5,  5,  5,  5,  5, 17, 18, 19])

In [35]:
jc = np.copy(j)  #Copies value , not reference
jc

array([ 5,  5,  5,  5,  5,  5,  5, 17, 18, 19])

In [36]:
np.random.seed(10)
abc = np.random.randint(1,10,(3,6))
abc

array([[5, 1, 2, 1, 2, 9],
       [1, 9, 7, 5, 4, 1],
       [5, 7, 9, 2, 9, 5]])

In [37]:
abc[0,0]                 #indexing in 2D array  (r,c)

5

In [38]:
abc[0][0]                #another way of indexing

5

In [39]:
abc[0, -1]

9

In [40]:
abc[:2]

array([[5, 1, 2, 1, 2, 9],
       [1, 9, 7, 5, 4, 1]])

In [41]:
abc[:2, 1:]

array([[1, 2, 1, 2, 9],
       [9, 7, 5, 4, 1]])

In [42]:
abc[2:, 2:]

array([[9, 2, 9, 5]])

In [43]:
v1 = np.array([3,4])    
v2 = np.array([5,12])

In [44]:
v1_mag = np.linalg.norm(v1)      #Magnitude of vector #np.linalg.norm
v1_mag

5.0

In [45]:
v2_mag= np.linalg.norm(v2)
v2_mag

13.0

In [46]:
np.dot(v1, v2)    #Dot_product = square of x-axis and y-axis and their sum

63

In [47]:
cos = np.dot(v1,v2)/(v1_mag * v2_mag)   #Cosine
cos

0.9692307692307692

In [48]:
angle_radian =np.arccos(cos)     #Changes to radian
angle_radian

0.24870998909352288

In [49]:
angle_d = (180* angle_radian)/ np.pi  #Changes to degree
angle_d

14.250032697803595

In [50]:
v1

array([3, 4])

In [51]:
v2

array([ 5, 12])

In [52]:
vc = np.cross (v1, v2)     #CrossProduct
vc

array(16)

In [53]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [54]:
A_inv = np.linalg.inv(A)   #inverse

In [55]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [56]:
A_det = np.linalg.det(A)     #Determinant
A_det

-2.0000000000000004

In [57]:
np.diag(A)  #Gives diagonal of matrix

array([1, 4])